services:
  viseron:
    image: roflcoopter/viseron:cuda
    container_name: viseron
    restart: unless-stopped
    privileged: true
    runtime: nvidia
    ports:
      - "8888:8888"
    volumes:
      - ./config:/config
      - ./recordings:/recordings
      - ./recordings/segments:/segments
      - ./recordings/events:/event_clips
      - ./recordings/thumbnails:/thumbnails
      - ./recordings/snapshots:/snapshots
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    shm_size: '2gb'